#!/bin/bash
DIRECTORY=$(dirname "$0")
echo "Changing to ${DIRECTORY}"
cd  "$DIRECTORY" || exit 1

echo "Run your project here."
echo "I can now push to the repo"
echo "Set local git config"

REQUESTS_CA_BUNDLE=pebble.minica.pem python3 main.py $@

