#!/bin/bash
DIRECTORY=$(dirname "$0")
echo "Changing to ${DIRECTORY}"
cd  "$DIRECTORY" || exit 1

echo "Run your project here."
echo "I can now push to the repo"
echo "Set local git config"

if [ $1 = "dns01" ]
then
    python3 dns_server.py $2 $3 $4 $5
elif [ $1 = "http01" ]
then
    echo "http01 not yet done"
else 
    echo "enter a dns01 or http01 keyword first"
fi

